### ISSUE TITLE
about CLIP model from?

### ISSUE THREAD

**Issue by Wangxuefeng92** [BoyuanJiang/FitDiT#2]
hi, sir, 
    thanks for your great work on FitDiT!  could you share us where to find 'OpenCLIP bigG/14' and 'CLIP-ViT/' model to embedding image? thanks a lot

**Comment by BoyuanJiang** [comment]
We use OpenCLIP bigG from https://huggingface.co/laion/CLIP-ViT-bigG-14-laion2B-39B-b160k and CLIP large from https://huggingface.co/openai/clip-vit-large-patch14
