### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by renderless** [BoyuanJiang/FitDiT#3]
Awesome works! Do you have plan to release the Complex Virtual Dressing Dataset (CVDD)?

**Comment by renderless** [comment]
Never mind. I found the dataset here, https://huggingface.co/datasets/BoyuanJiang/CVDD

**Comment by Holmes2002** [comment]
@renderless Hi, Can u share this dataset for me that this dataset hasn't found in huggingface anymore

**Comment by JunyaoHu** [comment]
+1 @renderless @Holmes2002 If it is convenient, could you share this it for me? :)
