### ISSUE TITLE
Model training

### ISSUE THREAD

**Issue by lizi85** [BoyuanJiang/FitDiT#5]
Thank you for the great work! I have a question regarding model training: 

Do you train the GarmentDiT model and the DenoisingDiT model from scratch or do you fine-tune a pre-trained DiT model? For how many training iterations are the two models trained for?

**Comment by BoyuanJiang** [comment]
We use SD3 medium as pretrained model and train approximately 30k step for each stage.

**Comment by sunny926sun** [comment]
i use 3GPU to train the model on 768*512, but the result is not good. i use bf16 , batchsize=12 and lr=1e-5.
the opened weights is trained in 1024*768 with 30k steps each stage?  could you give some training paramter about you , thank you very much.
