### ISSUE TITLE
2D DFT input image

### ISSUE THREAD

**Issue by seungyonglee0802** [BoyuanJiang/FitDiT#6]
Thanks for your nice work!

It's very interesting that you used imaged-based frequency loss with DFT to focus more on the components with significant gaps in the frequency domain during optimization.
I have one question on this part.
Did you use 2D DFT after **converting the image into the grey scale** (black and white image)?

Thanks in advance :)

**Comment by BoyuanJiang** [comment]
We use _freq = torch.fft.fft2(y, norm='ortho')_ to convert the image to its frequency domain, where y is the predicted-x0 image.

**Comment by seungyonglee0802** [comment]
Thanks for your comment! Then the `x_0` you mentioned above is a 3 channel RGB image, right?

**Comment by BoyuanJiang** [comment]
Yes it's a 3 channel RGB image.

**Comment by srijang97** [comment]
@BoyuanJiang Shouldn't the x_0 in  the fft function be the predicted image multiplied by the mask, and similarly for the original pixel values? Equation 6 in the FitDIT paper describes a matrix-wise multiplication operator ( xtr⊙mg) where you say  "mg represents the garment segmentation mask of xp obtained from human parsing model". I assume also that mg is not equal to the dilated relaxed mask and is instead purely based on the human parsing model?
